### PR TITLE
Add GitHub Actions for CI

### PR DESCRIPTION
**Pull request by nalimilan**
Based on the PkgTemplates file.

Updated version of https://github.com/JuliaLang/Example.jl/pull/52, with support for 32-bit (which is essential if we expect packages to run there).

### CODE REVIEW

**Comment by fredrikekre** [comment]
32 runs of CI :)

**Comment by nalimilan** [comment]
Yeah it's a lot. I guess we could disable a few of them (e.g. only keep one 32-bit run), but not sure which ones.

**Comment by fredrikekre** [comment]
I suggest commenting out such that only latest 1.x is run on the three OSs or something like that.

**Comment by rikhuijzer** [comment]
Shouldn't the separate travis and codecov files also be removed?

**Comment by nalimilan** [comment]
OK, I've tried something: test all platforms with latest Julia, test all Julia versions on 64-bit and 32-bit Linux. That gives 9 builds.

> Shouldn't the separate travis and codecov files also be removed?

We can probably do that, but that's not strictly necessary so I'm not sure. Probably better discuss this as a second step.

**Review by KristofferC — APPROVED** [review]
I think we can remove the travis, codecov and AV files after this

**Comment by nalimilan** [comment]
Of course I got the badge wrong! See https://github.com/JuliaLang/Example.jl/pull/57.

**Pull request merged**
